# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildNumber: '$(Build.BuildId)'
  registry.infra: docker.pkg.github.com/uanid/myserver
  registry.infra.key: Github-MyServer-Registry
  registryDeploy: ncpr.kr.ncr.ntruss.com

stages:
  - stage: Jar_Build_Deploy_Stage
    displayName: Build and Deploy Jar
    jobs:
      - job: Jar_Build_Job
        displayName: Build and Deploy Jar Job
        container:
          image: docker.pkg.github.com/uanid/myserver/my-maven:latest
          endpoint: Github-MyServer-Registry
        steps:
          - task: MavenAuthenticate@0
            inputs:
              mavenServiceConnections: 'Github MyServer Repository'
          - script: |
              ls -al $HOME/.m2/
              cat $HOME/.m2/settings.xml
              mvn clean package
          - publish: target/
            artifact: NotiApp
  - stage: Docker_Build_Stage
    displayName: Docker Image Build
    jobs:
      - job: Docker_Build_Job
        displayName: Docker Image Build
        container:
          image: gitlab/dind:latest
        steps:
          - download: current
            artifact: NotiApp
            patterns: "*.jar"
          - script: |
              cp ../NotiApp/*.jar .
              docker build -t $(registryDeploy)/notibot:$(buildNumber) -t $(registryDeploy)/notibot:latest .
              docker login $(registryDeploy) -u $(docker.username) -p $(docker.password)
              docker push $(registryDeploy)/notibot:$(buildNumber)
              docker push $(registryDeploy)/notibot:latest