# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build_Stage
    displayName: My First Build Stage
    jobs:
    - job: Build_Job
      displayName: My First Build Job
      container:
        image: docker.pkg.github.com/uanid/myserver/my-maven:latest
        endpoint: Github-MyServer-Registry
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo "Write your commands here"
            pwd 
            ls -al
            mvn clean package deploy
